name: happy_voice
description: Happy life
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^6.5.0
  permission_handler: ^11.3.0
flutter:
  uses-material-design: true
