name: happy_voice
description: Happy Voice App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.0.1
flutter:
  uses-material-design: true
